django_project/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name= 'home'),
    path('index/', views.homeindex, name= 'homeindex'),
    path('index1/', views.home1, name= 'home1'),
    path('index2/', views.home2, name= 'home2'),
    path('index3/', views.home3, name= 'home3'),
    path('index4/', views.home4, name= 'home4'),
    path('index5/', views.home5, name= 'home5'),
    path('index6/', views.home6, name= 'home6'),
    path('index7/', views.home7, name= 'home7'),
    path('index8/', views.home8, name= 'home8'),
    path('age_chart/', views.age_chart, name='age_chart'),
    path('sex_chart/', views.sex_chart, name='sex_chart'),
    path('perform_ocr', views.perform_ocr, name='perform_ocr'),
    path('admin/', admin.site.urls),    
]

django_project/models.py
from django.db import models


class Health(models.Model):
    patient_id = models.CharField(max_length=100, unique=True)
    patient_name = models.CharField(max_length=255)
    age = models.IntegerField()
    sex = models.CharField(max_length=255)
    reason_for_visit = models.CharField(max_length=255)
    image = models.ImageField(upload_to='static/images/')

    def __str__(self):
        return self.patient_name

django_project/forms.py
from django import forms
from .models import Health
from django.utils.translation import gettext_lazy as _

class HealthForm(forms.ModelForm):
    class Meta:
        model = Health
        fields = ['patient_id', 'patient_name', 'age', 'sex', 'reason_for_visit','image']

    def __init__(self, *args, **kwargs):
        self.language = kwargs.pop('language', None)
        super().__init__(*args, **kwargs)

self.fields['patient_id'].label = _('Patient ID')
self.fields['patient_name'].label = _('Patient Name')
self.fields['age'].label = _('Age')
self.fields['sex'].label = _('Sex')
self.fields['reason_for_visit'].label = _('Reason for Visit')
self.fields['image'].label = _('Image')






class InputForm(forms.Form):
    patient_id = forms.CharField(label='Patient ID', max_length=100)
    patient_name = forms.CharField(label='Patient Name', max_length=100)
    age = forms.IntegerField(label='Age')
    sex = forms.CharField(label='Sex', max_length=100)
    reason_for_visit = forms.CharField(label='Reason for visit', max_length=100)
    image = forms.ImageField(label='Image')

django_project/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Health
from .forms import HealthForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import os
from .forms import InputForm
import requests
import json
import sqlite3
import pandas as pd  
from django.db.models import Count


# Create your views here.
def home(request):
  return render(request, 'login.html')

def homeindex(request):
  return render(request, 'index.html')

def home1(request):
  if request.method == 'POST':
    form = HealthForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return HttpResponse(b'Data added successfully!')  # redirect to a new URL
  else:
    form = HealthForm()
  return render(request, 'index1.html', {'form': form})


def home2(request):
  selected_language = request.session.get('language')
  form = None

  if request.method == 'POST':
      if 'language' in request.POST:
          # User has selected a language
          selected_language = request.POST['language']
          request.session['language'] = selected_language
      else:
          # User has submitted the product form
          form = HealthForm(request.POST, request.FILES, language=selected_language)
          if form.is_valid():
              form.save()
              #return render(request, 'success.html', {'message': 'Data added successfully!'})
              return HttpResponse(b'Data added successfully!')


  if not selected_language:
      # If no language is selected, show the language selection form
      return render(request, 'index2.html')

  # Render the product form with the selected language
  form = form or HealthForm(language=selected_language)
  return render(request, 'index2.html', {'form': form})

def home3(request):
  form = HealthForm()
  if request.method == 'POST':
      form = HealthForm(request.POST, request.FILES)
      if form.is_valid():
          form.save()
          return HttpResponse(b'Data added successfully!')  # redirect to a new URL
  else:
      form = InputForm()
  return render(request, 'index3.html', {'form': form})

def home4(request):
  selected_language = request.session.get('language')
  form = HealthForm()

  if request.method == 'POST':
      form = HealthForm(request.POST, request.FILES)
      if form.is_valid():
          form.save()
          return HttpResponse(b'Data added successfully!')  # redirect to a new URL
  else:
      form = InputForm()

  return render(request, 'index4.html', {'form': form})

@csrf_exempt
def perform_ocr(request):
  if request.method == 'POST':
      username = 'your username'
      api_password = 'your password here'
      ocr_api_url = 'https://www.ocrwebservice.com/restservices/processDocument?gettext=true'

      image_file = request.FILES['image']

      try:
          data = {
            'file': image_file
          }
          auth = (username, api_password)

          response = requests.post(ocr_api_url, files=data, auth=auth)

          if response.ok:
              recognized_text = response.text
              return JsonResponse({'recognized_text': recognized_text})
          else:
              return JsonResponse({'error': 'Failed to perform OCR'}, status=500)
      except requests.RequestException as e:
          return JsonResponse({'error': f'Error performing OCR: {e}'}, status=500)
  else:
      return JsonResponse({'error': 'Method not allowed'}, status=405)

def home5(request):
  form = HealthForm()
  if request.method == 'POST':
      form = HealthForm(request.POST, request.FILES)
      if form.is_valid():
          form.save()
          return HttpResponse(b'Data added successfully!')  # redirect to a new URL
  else:
      form = InputForm()
  return render(request, 'index5.html', {'form': form})

def home6(request):
  form = HealthForm()
  if request.method == 'POST':
      form = HealthForm(request.POST, request.FILES)
      if form.is_valid():
          form.save()
          return HttpResponse(b'Data added successfully!')  # redirect to a new URL
  else:
      form = InputForm()
  return render(request, 'index6.html', {'form': form})
  #return render(request, 'index6.html')

def home7(request):
  emps = Health.objects.all()
  context = {
    'emps': emps
  }
  print(context)
  return render(request, 'index7.html',context)


def home8(request):
  # Get the age and total values from the database
  age_data = Health.objects.filter(age__in=[25, 36]).values('age').annotate(total=Count('age')).order_by('age')
  sex_data = Health.objects.values('sex').annotate(total=Count('sex'))
  # Prepare the data for the charts
  ages = [data['age'] for data in age_data]
  totals = [data['total'] for data in age_data]
  sexes = [data['sex'] for data in sex_data]
  sex_totals = [data['total'] for data in sex_data]
  # Render the template with the data
  return render(request, 'index8.html', {
    'ages': ages,
    'totals': totals,
    'sexes': sexes,
    'sex_totals': sex_totals,
  })


def age_chart(request):
  # Filtering the Health records for ages 25 and 36
  age_data = Health.objects.filter(age__in=[25, 36]).values('age').annotate(total=Count('age')).order_by('age')

  # Preparing data for the chart
  ages = [data['age'] for data in age_data]
  totals = [data['total'] for data in age_data]

  context = {
      'ages': ages,
      'totals': totals,
  }

  return render(request, 'index8.html', context)

def sex_chart(request):
  # Counting the number of occurrences of each sex
  sex_data = Health.objects.values('sex').annotate(total=Count('sex'))

  # Preparing data for the chart
  sexes = [data['sex'] for data in sex_data]
  totals = [data['total'] for data in sex_data]

  context = {
      'sexes': sexes,
      'totals': totals,
  }

  return render(request, 'index8.html', context)
    

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Text Mode</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style1.css" %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Text Indic</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/base3.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Voice</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/base6.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Combination</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/base7.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Records</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/base8.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Data Visualization Dashboard</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/index.html
{% extends "base_index.html" %}

{% block content %}
  <h1>Electronic Health Records (EHR) System</h1>
  <h1>MediTrack: Modernizing Patient Care Through Digital Records</h1>
  <hr>
    <img src="/static/images/images.jpg" alt="Healthcare Image" class="page-image" style="width: 600px; height: 300px;">
    <hr>
    <a href="/index1" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">1-Text</a>
    <a href="/index2" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">2-Text Indic</a>
    <a href="/index3" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">3-Voice</a>
    <a href="/index4" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">4-Voice Indic</a>
    <a href="/index5" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">5-Image</a>
    <a href="/index6" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">6-Combination of all 3</a>
    <a href="/index7" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">7-View Records</a>
    <a href="/index8" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">8-Data Visualization Dashboard</a>
    
    
    
{% endblock content %}

templates/index1.html
{% extends "base1.html" %}

{% block content %}
  <h1>Text mode</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Add Product</button>
  </form>
  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">Back</a>

{% endblock content %}

templates/index4.html
{% extends "base4.html" %}

{% block content %}
  <h1>Voice Indic Mode</h1>
  <hr>
  <h2>Select Language</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <label for="language">Language:</label>
      <select name="language" id="language" onchange="changeLanguage()">
        <option value="hindi">Select</option>
        <option value="tamil">Tamil</option>
        <option value="marathi">Marathi</option>
        <option value="hindi">Hindi</option>

      </select>

    </div>

    <div id="patient_id_section">
      <label for="id_patient_id" id="patient_id_label">Patient ID:</label>
      <input type="text" id="id_patient_id" name="patient_id">
    </div>
    <div>
        <label for="id_patient_name" id="patient_name_label">Patient Name:</label>
        <input type="text" id="id_patient_name" name="patient_name">

    </div>
    <div>
        <label for="id_age" id="age_label">Age:</label>
        <input type="text" id="id_age" name="age">

    </div>
    <div>
        <label for="id_sex" id='sex_label'>Sex:</label>
        <input type="text" id="id_sex" name="sex" step="0.01">

    </div>
    <div>
        <label for="id_reason_for_visit" id='reason_for_visit_label'>Reason for Visit:</label>
        <input type="text" id="id_reason_for_visit" name="reason_for_visit" step="0.01">

    </div>
    <div>
        <label for="id_image" id="image_label">Image:</label>
        <input type="file" id="id_image" name="image" accept="image/*">

    </div>
    <button type="submit">Submit</button>
  </form>

  <script>
    function changeLanguage() {
      var language = document.getElementById('language').value;
      var patientIdLabel = document.getElementById('patient_id_label');
      var patientIdInput = document.getElementById('id_patient_id');
      var patientNameLabel = document.getElementById('patient_name_label');
      var patientNameInput = document.getElementById('id_patient_name');
      var ageLabel = document.getElementById('age_label');
      var ageInput = document.getElementById('id_age');
      var sexLabel = document.getElementById('sex_label');
      var sexInput = document.getElementById('id_sex');
      var reasonforvisitLabel = document.getElementById('reason_for_visit_label');
      var reasonforvisitInput = document.getElementById('id_reason_for_visit');
      var imageLabel = document.getElementById('image_label');
      var imageInput = document.getElementById('id_image');

      if (language === "hindi") {
        patientIdLabel.innerText = "रोगी आईडी:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('रोगी आईडी');
        });
        patientIdInput.parentNode.appendChild(readAloudButton);

        patientNameLabel.innerText = "रोगी का नाम:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('रोगी का नाम');
        });
        patientNameInput.parentNode.appendChild(readAloudButton);

        ageLabel.innerText = "आयु:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('आयु');
        });
        ageInput.parentNode.appendChild(readAloudButton);

        sexLabel.innerText = "लिंग:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('लिंग');
        });
        sexInput.parentNode.appendChild(readAloudButton);

        reasonforvisitLabel.innerText = "यात्रा का कारण:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('यात्रा का कारण');
        });
        reasonforvisitInput.parentNode.appendChild(readAloudButton);

        imageLabel.innerText = "छवि:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('छवि');
        });
        imageInput.parentNode.appendChild(readAloudButton);



      } else if (language === "tamil") {


        patientIdLabel.innerText = "நோயாளி ஐடி:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('நோயாளி ஐடி');
        });
        patientIdInput.parentNode.appendChild(readAloudButton);

        patientNameLabel.innerText = "நோயாளி பெயர்:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('நோயாளி பெயர்');
        });
        patientNameInput.parentNode.appendChild(readAloudButton);

        ageLabel.innerText = "வயது:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('வயது');
        });
        ageInput.parentNode.appendChild(readAloudButton);

        sexLabel.innerText = "பாலினம்:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('பாலினம்');
        });
        sexInput.parentNode.appendChild(readAloudButton);

        reasonforvisitLabel.innerText = "வருகைக்கான காரணம்:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('வருகைக்கான காரணம்');
        });
        reasonforvisitInput.parentNode.appendChild(readAloudButton);

        imageLabel.innerText = "படம்:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('படம்');
        });
        imageInput.parentNode.appendChild(readAloudButton);

      } else if (language === "marathi") {


        patientIdLabel.innerText = "रुग्ण आयडी:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('रुग्ण आयडी');
        });
        patientIdInput.parentNode.appendChild(readAloudButton);

        patientNameLabel.innerText = "रुग्णाचे नाव:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('रुग्णाचे नाव');
        });
        patientNameInput.parentNode.appendChild(readAloudButton);

        ageLabel.innerText = "वय:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('वय');
        });
        ageInput.parentNode.appendChild(readAloudButton);

        sexLabel.innerText = "लिंग:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('लिंग');
        });
        sexInput.parentNode.appendChild(readAloudButton);

        reasonforvisitLabel.innerText = "भेटीसाठी कारण:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('भेटीसाठी कारण');
        });
        reasonforvisitInput.parentNode.appendChild(readAloudButton);

        imageLabel.innerText = "प्रतिमा:";
        var readAloudButton = document.createElement('button');
        readAloudButton.innerText = "Read Aloud";
        readAloudButton.addEventListener('click', function(event) {
          event.preventDefault();
          readAloud('प्रतिमा');
        });
        imageInput.parentNode.appendChild(readAloudButton);
      }
    }



    function readAloud(text) {
      event.stopPropagation();
      var speech = new SpeechSynthesisUtterance();
      speech.text = text;
      speech.lang = "hi-IN"; // Set the language code for Hindi (you can use "ta-IN" for Tamil, "mr-IN" for Marathi, etc.)

      speechSynthesis.speak(speech);
    }

    function readAloud1(text) {
      event.stopPropagation();
      var speech = new SpeechSynthesisUtterance();
      speech.text = text;
      speech.lang = "hi-IN"; // Set the language code for Hindi (you can use "ta-IN" for Tamil, "mr-IN" for Marathi, etc.)

      speechSynthesis.speak(speech);
    }

    function readAloud1(text) {
      event.stopPropagation();
      var speech = new SpeechSynthesisUtterance();
      speech.text = text;
      speech.lang = "hi-IN"; // Set the language code for Hindi (you can use "ta-IN" for Tamil, "mr-IN" for Marathi, etc.)

      speechSynthesis.speak(speech);
    }

    function readAloud2(text) {
      event.stopPropagation();
      var speech = new SpeechSynthesisUtterance();
      speech.text = text;
      speech.lang = "hi-IN"; // Set the language code for Hindi (you can use "ta-IN" for Tamil, "mr-IN" for Marathi, etc.)

      speechSynthesis.speak(speech);
    }

    function readAloud3(text) {
      event.stopPropagation();
      var speech = new SpeechSynthesisUtterance();
      speech.text = text;
      speech.lang = "hi-IN"; // Set the language code for Hindi (you can use "ta-IN" for Tamil, "mr-IN" for Marathi, etc.)

      speechSynthesis.speak(speech);
    }

    function readAloud4(text) {
      event.stopPropagation();
      var speech = new SpeechSynthesisUtterance();
      speech.text = text;
      speech.lang = "hi-IN"; // Set the language code for Hindi (you can use "ta-IN" for Tamil, "mr-IN" for Marathi, etc.)

      speechSynthesis.speak(speech);

    }


  </script>



  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">Back</a>

{% endblock content %}

templates/index5.html
{% extends "base5.html" %}

{% block content %}
  <h1>Image Mode</h1>
  <hr>
  <form id="productForm" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <label for="id_patient_id">Patient ID:</label>
      <input type="text" id="id_patient_id" name="patient_id">
      <input type="file" id="imageInput">
      <button type="button" id="ocrButton">OCR</button>
    </div>

    <div>
      <label for="id_patient_name">Patient Name:</label>
      <input type="text" id="id_patient_name" name="patient_name">
      <input type="file" id="imageInput1">
      <button type="button" id="ocrButton1">OCR</button>
    </div>

    <div>
      <label for="id_age">Age:</label>
      <input type="text" id="id_age" name="age">
      <input type="file" id="imageInput2">
      <button type="button" id="ocrButton2">OCR</button>
    </div>

    <div>
      <label for="id_sex">Sex:</label>
      <input type="text" id="id_sex" name="sex" step="0.01">
      <input type="file" id="imageInput3">
      <button type="button" id="ocrButton3">OCR</button>
    </div>

    <div>
      <label for="id_reason_for_visit">Reason for Visit:</label>
      <input type="text" id="id_reason_for_visit" name="reason_for_visit" step="0.01">
      <input type="file" id="imageInput4">
      <button type="button" id="ocrButton4">OCR</button>
    </div>

    <div>
      <label for="id_image">Image:</label>
      <input type="file" id="id_image" name="image" accept="image/*">

    </div>

    <button type="submit">Submit</button>
  </form>



  <script>
      const ocrButton = document.querySelector('#ocrButton');
      const imageInput = document.querySelector('#imageInput');
      const patientIdInput = document.querySelector('#id_patient_id');

      function handleOCRResponse(responseJson) {
        var recognizedText = responseJson.recognized_text.OCRText[0][0];
        patientIdInput.value = recognizedText; // Populate the recognized text into the SKU ID input field
      }

      ocrButton.addEventListener('click', async () => {
        const file = imageInput.files[0];
        const formData = new FormData();
        formData.append('image', file);

        try {
          const response = await fetch('/perform_ocr', {
            method: 'POST',
            body: formData
          });
          if (response.ok) {
            const data = await response.text();
            patientIdInput.value = data; // Populate the recognized text into the SKU ID input field
          } else {
            console.error('Failed to perform OCR');
          }
        } catch (error) {
          console.error('Error performing OCR:', error);
        }
      });
  </script>

  <script>
      const ocrButton1 = document.querySelector('#ocrButton1');
      const imageInput1 = document.querySelector('#imageInput1');
      const patientNameInput = document.querySelector('#id_patient_name');


      ocrButton1.addEventListener('click', async () => {
        const file = imageInput1.files[0];
        const formData = new FormData();
        formData.append('image', file);

        try {
          const response = await fetch('/perform_ocr', {
            method: 'POST',
            body: formData
          });
          if (response.ok) {
            const data = await response.text();
            patientNameInput.value = data; // Populate the recognized text into the SKU ID input field
          } else {
            console.error('Failed to perform OCR');
          }
        } catch (error) {
          console.error('Error performing OCR:', error);
        }
      });
  </script>

  <script>
      const ocrButton2 = document.querySelector('#ocrButton2');
      const imageInput2 = document.querySelector('#imageInput2');
      const ageInput = document.querySelector('#id_age');


      ocrButton2.addEventListener('click', async () => {
        const file = imageInput2.files[0];
        const formData = new FormData();
        formData.append('image', file);

        try {
          const response = await fetch('/perform_ocr', {
            method: 'POST',
            body: formData
          });
          if (response.ok) {
            const data = await response.text();
            ageInput.value = data; // Populate the recognized text into the SKU ID input field
          } else {
            console.error('Failed to perform OCR');
          }
        } catch (error) {
          console.error('Error performing OCR:', error);
        }
      });
  </script>

  <script>
      const ocrButton3 = document.querySelector('#ocrButton3');
      const imageInput3 = document.querySelector('#imageInput3');
      const sexInput = document.querySelector('#id_sex');


      ocrButton3.addEventListener('click', async () => {
        const file = imageInput3.files[0];
        const formData = new FormData();
        formData.append('image', file);

        try {
          const response = await fetch('/perform_ocr', {
            method: 'POST',
            body: formData
          });
          if (response.ok) {
            const data = await response.text();
            sexInput.value = data; // Populate the recognized text into the SKU ID input field
          } else {
            console.error('Failed to perform OCR');
          }
        } catch (error) {
          console.error('Error performing OCR:', error);
        }
      });
  </script>

  <script>
      const ocrButton4 = document.querySelector('#ocrButton4');
      const imageInput4 = document.querySelector('#imageInput4');
      const reasonforvisitInput = document.querySelector('#id_reason_for_visit');


      ocrButton4.addEventListener('click', async () => {
        const file = imageInput4.files[0];
        const formData = new FormData();
        formData.append('image', file);

        try {
          const response = await fetch('/perform_ocr', {
            method: 'POST',
            body: formData
          });
          if (response.ok) {
            const data = await response.text();
            reasonforvisitInput.value = data; // Populate the recognized text into the SKU ID input field
          } else {
            console.error('Failed to perform OCR');
          }
        } catch (error) {
          console.error('Error performing OCR:', error);
        }
      });
  </script>
  
  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: yellow; color: black; padding: 10px 20px; border: none; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block;">Back</a>
{% endblock content %}